Social_webpage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('social_web.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
    path('ranking/', views.image_ranking, name='ranking'),
]

social_web/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.user_login),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('password-change/', auth_views.PasswordChangeView.as_view(), name="password_change"),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('list/', views.user_list, name='user_list'),
    path('user/follow/', views.user_follow, name='user_follow'),
    path('users/<username>/', views.user_detail, name='user_detail'),


]

social_web/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    dob = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to= 'users/%Y/%m/%d/', blank=True)

    def __str__(self):
        return f'Profile of {self.user.username}'

class Contact(models.Model):
    user_from = models.ForeignKey('auth.User', related_name='rel_from_set', on_delete=models.CASCADE)
    user_to = models.ForeignKey('auth.User', related_name='rel_to_set', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        indexes = [models.Index(fields=['-created'])]
        ordering = ['-created']
    
    def __str__(self):
        return f'{self.user_from} follows {self.user_to}'

user_model = get_user_model()
user_model.add_to_class('following', models.ManyToManyField('self', through=Contact, related_name='followers', symmetrical=False))

social_web/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class loginform(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(widget=forms.PasswordInput)
    

class Register_form(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    confirm_password = forms.CharField(label="Confirm Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "is_staff"]

    def clean_password2(self):
        pswd1 = self.cleaned_data.get("password")
        pswd2 = self.cleaned_data.get("confirm_password")

        if pswd2 != pswd1:
            raise forms.ValidationError("Password mismatch")
        
        return pswd2

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError('Email already in use')
        return data
    
class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
    
    def clean_email(self):
        data = self.cleaned_data['email']
        qs = User.objects.exclude(id=self.instance.id).filter(email=data)
        if qs.exists():
            raise forms.ValidationError('Email alreadyh in use')
        return data
            
class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['dob', 'photo']

social_web/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import loginform, Register_form, UserEditForm, ProfileEditForm
from django.contrib import messages
from django.views.decorators.http import require_POST
from .models import Profile, Contact
from actions.utils import create_action
from actions.models import Action

# Create User login view.
def user_login(request):
    if request.method == "POST":
        # create form instance
        form = loginform(request.POST)
        # check if valid inputs are provided
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd["username"], password=cd["password"])
            if user is not None:
                # add user to current session
                login(request, user)
                return HttpResponse("User Authenticated")
            else: 
                return HttpResponse("Invalid credentials")
    else:
        form = loginform()

    return render(request, "social_web/login.html", {'form': form})


@login_required
def dashboard(request):
    actions = Action.objects.exclude(user=request.user)
    following_ids = request.user.following.values_list('id', flat=True)

    if following_ids:
        actions = actions.filter(user_id__in=following_ids)
    # retrieve first 10 actions
    actions = actions.select_related('user', 'user__profile').prefetch_related('target')[:10]
    return render(request, 'social_web/dashboard.html', {'dashboard': dashboard,
                                                         'section': 'dashboard',
                                                         'actions': actions})


def register(request):
    if request.method == "POST":
        user_form = Register_form(request.POST)

        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data["password"])
            new_user.save()

            Profile.objects.create(user=new_user)
            create_action(new_user, 'has created an account')
            return render(request, 'social_web/register_done.html', {'new_user': new_user})
    else:
        user_form = Register_form()
        
    return render(request, 'social_web/register.html', {'user_form': user_form})

@login_required
def edit(request):
    success = None
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            success = True
            messages.success(request, "profile updated successfully")
        else: 
            success = False
            messages.error(request, 'Error updating the profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    
    return render(request, 'social_web/edit.html', {'user_form': user_form,
                                                    'profile_form': profile_form,
                                                    'success': success})

@login_required
def user_list(request):
    users = User.objects.filter(is_active=True)
    profiles = Profile.objects.all()
    return render(request, 'social_web/users/list.html', {'section': 'people',
                                                          'users': users,
                                                          'profiles': profiles})

@login_required
def user_detail(request, username):
    user = get_object_or_404(User, username=username, is_active=True)
    profile = Profile.objects.get(user= user)
    return render(request, 'social_web/users/detail.html', {"section": 'people',
                                                            "user": user,
                                                            'profile': profile})

@require_POST
@login_required
def user_follow(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            if action == 'follow':
                Contact.objects.get_or_create(user_from = request.user,
                                              user_to = user)
                create_action(request.user, 'is following', user)
            else:
                Contact.objects.filter(user_from=request.user,
                                       user_to=user).delete()
            return JsonResponse({'status': 'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status': 'error'})
    return JsonResponse({'status': 'error'})
                

social_web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title> {% block title %} Social Webpage {% endblock%} </title>
        <link rel="stylesheet" href="{% static "social_web/css/base.css" %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid HEADERS">
                <a class="navbar-brand" href='#'> Social Website </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText " aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"> </span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText items">
                    {% if request.user.is_authenticated %}
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0 menu">
                            <li class="navbar-item" >
                                {% if section == "dashboard" %}
                                    <a class="nav-link active itemNavbar" href="{% url 'dashboard' %}"> Dashboard </a>
                                {% else %}                                                       
                                    <a class="nav-link itemNavbar" href="{% url 'dashboard' %}"> Dashboard </a>
                                {% endif  %}
                            </li>
                            <li class="navbar-item">
                                {% if section  %} 
                                    {% if section == "images" %}
                                    <a class="nav-link active itemNavbar" href="{% url 'images:list' %}"> Images </a>
                                    {% elif section == "imageRanking" %}
                                    <a class="nav-link active itemNavbar" href="{% url 'images:list' %}"> Images Ranking </a>
                                    {% elif section == "imagedetail" %}
                                    <a class="nav-link active itemNavbar" href="{% url 'images:list' %}"> Image Detail </a> 
                                    {% elif section == "people" or section == "dashboard" %}
                                    <a class="nav-link itemNavbar" href="{% url 'images:list' %}"> Images </a>
                                    {% endif %}
                                {% endif %}
                            </li>
                            <li class="navbar-item" >
                                {% if section == 'people' %} 
                                <a class="nav-link active itemNavbar" href="{% url 'user_list' %}"> People</a>
                                {% else %}
                                <a class="nav-link itemNavbar" href="{% url 'user_list' %}"> People</a>
                                {% endif%}
                            </li>
                            <li class="navbar-item">
                                <a class="nav-link itemNavbar" href="{% url 'password_change' %}"> Change password </a>
                            </li> 
                        </ul>
                    {% else %}
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class-"navbar-item" >
                                Login Page
                            </li>
                        </ul>
                    {% endif %}
                    
                        
                    <span class="navbar-text userGreeting">
                    {% if request.user.is_authenticated %}
                        <span>
                        Welcome {{request.user.get_full_name}} 
                        </span>
                        <form id="logout-form" method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="logoutbtn">logout</button>
                        </form>
                    {% else %}
                        <a class="nav-link" href="{% url 'login' %}"> Login </a>
                    {% endif %}
                    </span>

                
                </div>
            </div>
        </nav>
        {% if messages %} 
            {% if success %}
                {% for message in messages %}
                    <div class='progress mt-2 px-3' role='progressbar' aria-label="Success example" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="height: 30px">
                        <div class="progress-bar bg-success" style="width: 100%"> {{message|safe}} </div>
                    </div>
                {% endfor %}
            {% else %}
                {% for message in messages %}
                <div class='progress mt-2' role='progressbar' aria-label="Danger example" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="height: 30px">
                    <div class="progress-bar bg-danger" style="width: 100%"> {{message|safe}} </div>
                </div>
                {% endfor %}
            {% endif %}
         {% endif %}
        <div>
            {% block content %} {% endblock%}
        </div>
        <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
        <script>
            const csrf_token = Cookies.get('csrftoken');
            console.log('csrf_token', csrf_token);
            document.addEventListener('DOMContentLoaded', (event) => {
                {% block domready %} 

                {% endblock %}
            })
        </script>
    </body>
</html>