Social_webpage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('social_web.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
    path('ranking/', views.image_ranking, name='ranking'),
]

images/models.py
from django.db import models
from django.conf import settings 
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.
class image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='image_created',
                             on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150, blank=True)
    url = models.URLField(max_length=2000)
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True)

    user_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                       related_name = 'image_liked',
                                       blank=True)

    total_likes = models.PositiveIntegerField(default=0)

    class Meta:
        indexes = [
            models.Index(fields=['-created']),
            models.Index(fields=['-total_likes']),
            ]
        ordering = ['-created']
    
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs) 
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])
    

images/forms.py
from django import forms
from .models import image
from django.core.files.base import ContentFile
from django.utils.text import slugify
import requests


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = image
        fields = ['title', 'url', 'description']
        widgets = {
            'url' : forms.HiddenInput
        }
    
    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['png', 'jpg', 'jpeg']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('given url does not match with image extension')
        return url
    
    def save(self, force_insert=False, force_update=False, commit=True):
        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        name = slugify(image.title)
        extension = image_url.rsplit('.',1)[1].lower()
        image_name = f'{name}.{extension}'
        # download image from url
        response = requests.get(image_url)
        image.image.save(image_name, ContentFile(response.content), save=False)

        if commit:
            image.save()
        
        return image

images/views.py
from django.shortcuts import render, redirect
from .forms import ImageCreateForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required 
from django.views.decorators.http import require_http_methods, require_POST
from django.shortcuts import get_object_or_404
from django.http import JsonResponse, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from actions.utils import create_action 
from .models import image
import redis
from django.conf import settings

# connect to redis
r = redis.Redis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB)

@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_image = form.save(commit=False)
            new_image.user = request.user
            new_image.save()
            create_action(request.user, 'bookmarked image', new_image)
            messages.success(request, 'image added successfully')
            return redirect(new_image.get_absolute_url())
        
    else:
        form = ImageCreateForm(data=request.GET)
    

    return render(request, 'images/image/create.html', {'form': form,
                                                        'section_image':'images',
                                                        'section_dshbrd': 'dshbrd'})


def image_detail(request, id, slug):
    image_view = get_object_or_404(image, id=id, slug=slug)
    # increment image view by 1
    total_views = r.incr(f'image_view:{image_view.id}:views')
    # increment image ranking by 1
    r.zincrby('image_ranking', 1, image_view.id)

    return render(request, 'images/image/detail.html',
                  {'section': 'imagedetail',
                   'image': image_view,
                   'success': True,
                   'total_views': total_views})

@login_required
# @require_http_methods(["POST"])
@require_POST
def image_like(request):
    image_id = request.POST.get("id")
    action = request.POST.get('action')
    if image_id and action:
        try:
            Image = image.objects.get(id=image_id)
            if action == 'like':
                Image.user_like.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                Image.user_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except image.DoesNotExist:
            pass
    return JsonResponse({'status': 'error'}) 


@login_required
def image_list(request):
    images = image.objects.all()
    paginator = Paginator(images, 6)
    page = request.GET.get('page')
    images_only = request.GET.get('images_only')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if images_only:
            return HttpResponse('')
        images = paginator.page(paginator.num_pages)
    if images_only:
        return render(request, 'images/image/list_images.html',{'section': 'images',
                                                                'images': images})
    return render(request, 'images/image/list.html', {'section':'images',
                                                      'images': images})

@login_required
def image_ranking(request):
    image_ranking = r.zrange('image_ranking', 0 , -1, desc=True)[:10]
    image_ranking_ids = [int(id) for id in image_ranking]

    most_viewed = list(image.objects.filter(id__in=image_ranking_ids))
    most_viewed.sort(key=lambda x:image_ranking_ids.index(x.id))
    return render(request, 'images/image/ranking.html', {'section': "imageRanking",
                                                         'most_viewed': most_viewed})

images/templates/images/image/create.html
{% extends 'base.html' %}

{% block title %} Bookmark image {% endblock%}

{% block content %}

    <img src="{{request.GET.url}}" >
    <form method='post'>
        {{form.as_p}}
        {% csrf_token %}
        <input type='submit' value='Bookmark it'>
    </form>
{% endblock %}

images/templates/images/image/detail.html
{% extends 'base.html' %}

{% block title %} {{ image.title }} {% endblock %}

{% block content %}
    {% load thumbnail %}
    <div class="bookmarked_img_detail">
        <a href="{{image.image.url}}">
            <img src='{% thumbnail image.image 700x0 %}'>
        </a>
        {% with total_likes=image.user_like.count users_like=image.user_like.all %}
        <div class="bookmark_pg_content">
            <div class="bookmark_content_container">
                
                <span class='count'>
                    <span class='total'>
                        {{total_likes}} 
                    </span>
                    like{{total_likes|pluralize}}
                </span>
                <span>
                    {{total_views}} view{{total_views|pluralize}}
                </span>
                <a href='#' data-id="{{image.id}}" data-action="{% if request.user in users_like %}un{% endif %}Like" class="like" >
        
                    {% if request.user not in users_like %}
                        like
                    {% else %}
                        Unlike 
                    {% endif %}
                </a>
            </div>
            <div class="bookmark_descrip">
                <h4> Description: </h4>
                <p>
                    {{image.description|linebreaks}}
                </p>
            </div>
        </div>
    </div>
        <div class="userlike">
            {% for user in image.user_like.all %}
                <div class="dsplyusers">
                {% if user.profile.photo %}
                    <img src="{% thumbnail user.profile.photo 50x50 %}">
                {% endif %}
                <a href="{{ user.get_absolute_url }}"> {{ user.get_full_name }} </a>
                </div>
                <br>               
            {% empty %}
                No likes
            {% endfor %}
        </div>
    {% endwith %}

{% endblock %}


{% block domready %}
const url = '{% url "images:like" %}'
var options = {
    method: 'POST',
    headers: {'X-CSRFToken': csrf_token},
    mode: 'same-origin' 
}
document.querySelector('a.like').addEventListener('click', function(e){
    e.preventDefault();
    var likeButton = this;

var formData = new FormData();
formData.append('id', likeButton.dataset.id);
formData.append('action', likeButton.dataset.action);
options['body'] = formData;

var resp = fetch(url, options);
console.log(resp);

fetch(url, options).then(response => response.json()).then(data => {
    if (data['status'] === 'ok') {
        var previousAction = likeButton.dataset.action;

        var action = previousAction === 'like' ? 'unlike':'like';
        likeButton.dataset.action = action;
        likeButton.innerHTML = action;

        var likeCount = document.querySelector('span.count .total');
        var totalLikes = parseInt(likeCount.innerHTML);
        likeCount.innerHTML = previousAction === 'like' ? totalLikes + 1 : totalLikes - 1;

    }
})
});
{% endblock %}

images/templates/images/image/list.html
{% extends 'base.html' %}

{% block title %} Images Bookmarked {% endblock %}

{% block content %}
    <div class="imagelist">
        <span class="Header">
            <h2> Bookmarked images </h2>
        </span>
        <span class="imgRanking"> 
            <a href="{% url 'images:ranking' %}"> Image Ranking </a>
        </span>
        {% include 'images/image/list_images.html' %}
    </div>
{% endblock %}

images/templates/images/image/list_images.html
{% load thumbnail %}


<div class="container text-center mt-4">
    <div class="row row-cols-2">
    {% for image in images %}
        <div class="col">
            <a href="{{image.get_absolute_url}}">
                <img src='{% thumbnail image.image 300x300 crop="smart" %}'>
            </a>
            <p> {{image.title}} </p>
        </div>
    {% endfor %}
    </div>
</div>

{% include "pagination.html" with page=images %}

images/templates/images/image/ranking.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Image ranking {% endblock %}

{% block content %}
    <h1> Images ranking </h1>
    <table class="imageRanking">
        <tr>
            <th class="width"> S.no </th>
            <th> Title </th>
            <th class="imageWidth"> Image thumbnail </th>
        </tr>
        {% for image in most_viewed %}
            <tr>
                <td class="width"> {{ forloop.counter }} </td>
                <td class="titleWidth"> 
                    <a href="{{ image.get_absolute_url }}">
                        {{ image.title }}
                    </a> 
                </td>
                <td class="imageWidth">
                    <a href="{{ image.get_absolute_url }}">
                        {% thumbnail image.image 80x80 as img%}
                        <img src="{{ img.url }}">
                    </a>
                </td>
            </tr>
        {% endfor %}
        </table>
{% endblock %}